### ISSUE TITLE
Warning: Prop 'className' did not match

### ISSUE THREAD

**Issue by Eakam1007** [DevelopingSpace/starchart#237] opened 2023-02-17 20:02 UTC
I saw this error in the dev console in Microsoft Edge (chromium version) while running the app locally. This does not show up on Firefox or Chrome

<img width="968" alt="image" src="https://user-images.githubusercontent.com/67077705/219780900-4eab0083-0c3b-4aae-8ff1-72e312f19fb4.png">

Could possibly be related to https://stackoverflow.com/questions/64336286/next-js-react-app-with-styled-components-warning-prop-classname-did-not-matc but more information is required

### Steps to reproduce
- Run the app locally
- Open dev console while navigating to app on Microsoft Edge (chromium)
- Check for error

**Comment by humphd** [comment] 2023-03-07 16:50
I can't reproduce this with Edge on my Mac.  Can anyone else confirm it still exists?

**Comment by Eakam1007** [comment] 2023-03-08 19:28
Can confirm that this still happens on Edge on Windows. I believe it might not happen on Mac cause Edge on Mac uses Webkit or something else

**Comment by Ririio** [comment] 2023-03-12 13:21
![image](https://user-images.githubusercontent.com/32577022/224547329-8f79ca70-1aeb-4582-8b50-406c8bd68e2a.png)

Weird... I can't reproduce the same error on windows

**Comment by Eakam1007** [comment] 2023-03-12 21:03
Oh, I looked at this again and saw that the error message shows because of the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) extension. 
I also saw another warning when I clicked on Manage DNS Records. I am not sure if these are something that we should look into:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/67077705/224573527-2ffe27f9-ffd0-421f-8c6b-992e049ea254.png">

**Comment by Ririio** [comment] 2023-03-13 03:38
That's really odd... I have [react](https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil) for edge installed too, and I checked opera gx for the same issue, and I don't receive the error. We might need another person here to check this out, and figure out if this isn't an individual issue...

Here's an issue I get from chrome which is different

![image](https://user-images.githubusercontent.com/32577022/224602718-2a465908-edd0-413c-aa76-51d08bd5101b.png)

**Comment by humphd** [comment] 2023-04-10 14:53
Let's close this and re-open if we find that it's happening a lot in the future.  Not enough of us can reproduce.

**Closed by humphd** 2023-04-10 14:53 UTC
Labels: bug
