### ISSUE TITLE
Unable to create certificate order on production

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#651] opened 2023-04-19 19:35 UTC
I've fixed the issue with AWS on production, and now it looks like we have a new problem with Let's Encrypt:

```
{"level":"info","message":"Creating certificate order for davidhumphrey.mystudentproject.ca","timestamp":"2023-04-19T19:26:02.292Z"}
{"level":"debug","message":"Initializing Let's encrypt","timestamp":"2023-04-19T19:26:02.292Z"}
{"level":"debug","message":"Creating ACME order for davidhumphrey.mystudentproject.ca","timestamp":"2023-04-19T19:26:03.119Z"}
{"level":"info","message":"Order created successfully","timestamp":"2023-04-19T19:26:03.735Z"}
{"clientVersion":"4.13.0","code":"P2002","level":"error","message":"Failed to update certificate 9 in db \nInvalid `prisma.certificate.update()` invocation:\n\n\nUnique constraint failed on the constraint: `Certificate_orderUrl_key`","meta":{"target":"Certificate_orderUrl_key"},"stack":"Error: \nInvalid `prisma.certificate.update()` invocation:\n\n\nUnique constraint failed on the constraint: `Certificate_orderUrl_key`\n    at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)\n    at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)\n    at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)\n    at t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)\n    at Worker.import_bullmq.Worker.connection [as processFn] (/app/build/index.js:1965:7)\n    at Worker.processJob (/app/node_modules/bullmq/src/classes/worker.ts:667:22)\n    at Worker.retryIfFailed (/app/node_modules/bullmq/src/classes/worker.ts:858:16)","timestamp":"2023-04-19T19:26:03.747Z"}
```

I think we're failing here:

https://github.com/DevelopingSpace/starchart/blob/main/app/queues/certificate/order-creator-worker.server.ts#L118-L127

In the database, the `orderUrl` is `NULL`:

<img width="1602" alt="Screenshot 2023-04-19 at 3 34 05 PM" src="https://user-images.githubusercontent.com/427398/233181065-c50115f9-c8e9-4af0-a5bf-9da6ba069e1b.png">

I've tried starting and stopping the containers a few times, and retried after the process fails.  The same error happens every time.

cc @dadolhay.

**Comment by humphd** [comment] 2023-04-19 22:06
cc @cychu42, in case there's some db thing I'm missing.

**Comment by dadolhay** [comment] 2023-04-19 23:22
@humphd 
Yes, it seems to be a db issue
Unique constraint failed on the constraint: `Certificate_orderUrl_key`
So the certificate orderUrl is not unique ... not sure how can that be

**Comment by dadolhay** [comment] 2023-04-19 23:27
I think the following has happened:
- Cert creation failed because of DNS issues
- New cert request was started
- Order was the exact same as before, and since there was a pending order with ACME, it returned the same order to you again

- System cannot store the order as it is the duplicate of a previous one

**Comment by dadolhay** [comment] 2023-04-19 23:39
PR added, you will also have to go in and manually null out the orderUrl of certificates that are in a failed state

**Comment by humphd** [comment] 2023-04-20 00:10
Great detective work, @dadolhay! Thanks for jumping on this.  I'll fix db now in preparation for landing this.

**Closed** 2023-04-20 00:15 UTC
