### ISSUE TITLE
Feat: Domains Table

### ISSUE THREAD

**Issue by Myrfion** [DevelopingSpace/starchart#137] opened 2023-02-06 16:58 UTC
### Overview
This task aims to create a component named `DomainsList.tsx` that will render domains list and trigger certain actions.  

### Design
Refer to Figma for the design

### Implementation
Table should be done with Chakra UI table: https://chakra-ui.com/docs/components/table

Props should look something like:
```typescript
interface DomainsListProps {
 domains: Domain[]
 onAction: (action: DomainsListAction) => void
}

type DomainsListAction = 'EDIT' | 'DELETE' | 'RENEW'  
```

**Comment by humphd** [comment] 2023-02-06 23:32
I would use `RENEW` vs. `REFRESH` to better reflect what it does.

**Comment by Eakam1007** [comment] 2023-02-12 09:54
Is this a duplicate of #46 ?

**Closed** 2023-02-13 15:51 UTC
Labels: front-end
