### ISSUE TITLE
Notify users about SSL certificate completion status through email

### ISSUE THREAD

**Issue by cychu42** [DevelopingSpace/starchart#9] opened 2023-01-24 18:21 UTC
After a user sends a request to get a certificate, we should avoid keeping them waiting in front of the screen until the task is complete.
Therefore, we can state they will be notify of the completion status through email, after they make a request.
The email can contain a link for the user to retrieve the certificate, or let them know if the process runs into issues.

**Comment by humphd** [comment] 2023-03-31 02:41
Dupe of #109

**Closed by humphd** 2023-03-31 02:41 UTC
Labels: category: notifications, new feature, area: functionality
